### ISSUE TITLE
train_val does not work

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [leeyoshinari/YOLO_v2#4]
Hello,

when I run

```
python3 train_val.py
```

I get the following error:
```
Traceback (most recent call last):
  File "train_val.py", line 17, in <module>
    from yolo.yolo_v2 import yolo_v2
  File "/Users/vaevictis/Desktop/yolo-docker/YOLO_v2/yolo/yolo_v2.py", line 141
    best_box = tf.to_float(tf.equal(iou, tf.reduce_max(iou, axis = 3, True)))
                                                                     ^
SyntaxError: positional argument follows keyword argument
```

**Comment by FrancescoSaverioZuppichini** [comment]
So?
